version: '3'

services:
  database:
    container_name: 'api-nest'
    image: 'postgres:13-alpine'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=api-nest-study
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: unless-stopped